clone:
    hg:
        image: plugins/hg

pipeline:
    tox:
        image: ${IMAGE}
        environment:
            - CFLAGS=-O0
            - DB_CACHE=/cache
            - TOX_TESTENV_PASSENV=CFLAGS DB_CACHE
            - POSTGRESQL_URI=postgresql://postgres@postgresql:5432/
        commands:
            - pip install tox
            - tox -e "${TOXENV}-${DATABASE}"

services:
    postgresql:
        image: postgres
        when:
            matrix:
                DATABASE: postgresql

matrix:
    include:
        - IMAGE: python:2.7
          TOXENV: py27
          DATABASE: sqlite
        - IMAGE: python:2.7
          TOXENV: py27
          DATABASE: postgresql
